### ISSUE TITLE
I seem to have missed a step - no console

### ISSUE THREAD

**Issue by jfabernathy** [warpme/miniarch#1]
I'm, trying to test this on a Raspbery Pi 4 4GB. I downloaded MiniArch-20230106-6.1.5-board-sm1.tanix_tx5_plus-board-rpi34.mainline64-SD-Image.img.xz and flashed it to a microSD card using the Raspberry Pi Imager 1.7.2.

I can see the Uboot text on my Monitor but after the message Starting Kernel, the Monitor goes blank and I have not idea what to do next.

**Comment by warpme** [comment]
Ah - 4G RPI :-(
On the BOOT partion there is file boot-debug.scr
May you pls rename it it boot.scr
This will give us kernel debug verbosity on screen - and maybe we will see where kernel traps...

**Comment by jfabernathy** [comment]
![Uploading 20230114_152118.jpg…]()

**Comment by jfabernathy** [comment]
Seems to be looping

**Comment by jfabernathy** [comment]
![20230114_152118](https://user-images.githubusercontent.com/46226222/212495218-7cf62aad-203c-4e2a-82af-c9af5bfa39ad.jpg)

**Comment by warpme** [comment]
it looks to me like tfpt interfering with local boot.
May you pls try with disconnected Eth cable?

**Comment by jfabernathy** [comment]
![20230114_153242](https://user-images.githubusercontent.com/46226222/212495536-1ffd1ede-269f-4651-a2f0-453632387ec4.jpg)

**Comment by warpme** [comment]
give me some time - i need to ask rpi guys...

**Comment by jfabernathy** [comment]
BTW, I put the SD card into a RPI 3B+ and got the same behavior with and without the Ethernet connected.

**Comment by jfabernathy** [comment]
Not critical, just playing with it until my NFL football game comes on.

**Comment by warpme** [comment]
huh - i just tested on mine rpi3 model B v1.2.
boots ok
this is really frustrating :-(

let me ask rpi guys where issue might be...
(btw: do you know what eeprom ver you have in yours rpi3/4)?

**Comment by jfabernathy** [comment]
On the rpi4 
![20230114_160258](https://user-images.githubusercontent.com/46226222/212496732-56367d00-6903-4e99-a149-58dde59d7ae3.jpg)

**Comment by jfabernathy** [comment]
The rpi3 B+ is a rev 1.3

**Comment by jfabernathy** [comment]
I when back to what I usually run on the RPI4. It's EndeavourOS ARM.

Linux rpi4-mythtv 5.15.84-4-rpi-ARCH #1 SMP PREEMPT Wed Jan 11 14:06:42 MST 2023 aarch64 GNU/Linux

NOTE the Ethernet port is not eth0, it's end0. Not sure when that changes

2: end0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether e4:5f:01:79:34:8a brd ff:ff:ff:ff:ff:ff
    inet 169.254.197.102/16 brd 169.254.255.255 scope link noprefixroute end0
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether e4:5f:01:79:34:8b brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.115/24 brd 192.168.0.255 scope global dynamic noprefixroute wlan0
       valid_lft 6857sec preferred_lft 6857sec
    inet6 fe80::2208:402d:45c7:e23e/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

model name      : ARMv8 Processor rev 3 (v8l)
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : c03114
Serial          : 100000004ba90648
Model           : Raspberry Pi 4 Model B Rev 1.4

**Comment by warpme** [comment]
If you still have energy to play with boot issue, may you try new versions i just uploaded?
There are:

- universal rpi34 image with latest uboot
- dedicated rpi3 image with latest uboot
- dedicated rpi4 image with latest uboot

**Comment by jfabernathy** [comment]
I tried the dedicated rpi4. No luck.
![20230115_121128](https://user-images.githubusercontent.com/46226222/212556131-1c612970-9859-4483-8511-9f3b985c86b9.jpg)

**Comment by jfabernathy** [comment]
Just to try something I setup a microSD card the way they say to on archlinux ARM site for the RPI4. That wouldn't boot either.  I posted that in the Archlinuxarm.org forum.
[https://archlinuxarm.org/forum/viewtopic.php?f=65&t=16325](url)

I have had good luck with EOS ARM and Ubuntu 22.10 ARM. both work great with GFX acceleration.

**Comment by warpme** [comment]
Most probable theory is incompatibility of SD card you are using & u-boot sd card driver.
Your's screenshots showing issue is very early - at tpl (third program loader which is u-boot). This happens before control is passed to kernel.
This limits suspected components just to: sd card; rpi firmware and u-boot.  
Is it possible to try with different vendor sd card?

**Comment by warpme** [comment]
I will also try to build image with most recent rpi firmware

**Comment by jfabernathy** [comment]
The cards from yesterday were SanDisk. Today I used Samsung. Both cards with RPi OS.
![20230115_154450](https://user-images.githubusercontent.com/46226222/212566447-a66530af-4922-4a98-89d9-79cdb81049a5.jpg)

**Comment by jfabernathy** [comment]
There seems to be similar problems reported over on the archlinuxarm.org forum.
[https://archlinuxarm.org/forum/viewtopic.php?f=65&t=16310](url)

[https://archlinuxarm.org/forum/viewtopic.php?f=65&t=16243](url)

**Comment by warpme** [comment]
Ah - this is very good info!
As for test: may you pls burn latest rpi34 image, replace boot.scr to attached one and try?
[boot.scr.zip](https://github.com/warpme/miniarch/files/10424410/boot.scr.zip)

**Comment by jfabernathy** [comment]
yes that boots to kernel 6.1.5 with Ethernet connected with IP address from local router.
