### ISSUE TITLE
SSV6256p / SV6256P wifi driver for kernels >4.4.x

### ISSUE THREAD

**Issue by mercs759** [warpme/miniarch#10]
Hi,
(my system setup and other infos are in previous issue)

H313's MMC/SDIO bus correctly detects the presence of an SDIO card (its a wifi chip marked "SV6256P") , and i can find its details under : 

/sys/bus/mmc/devices/mmc3:0001/uevent 
MMC_TYPE=SDIO
SDIO_ID=3030:3030
SDIO_REVISION=8.0
SDIO_INFO1=SouthSiliconValley.Inc.
SDIO_INFO2=Turismo
SDIO_INFO3=0
SDIO_INFO4=00

(I don't know why it's put under "mmc3" : there's no mmc3 reference in miniarch dtb or in my filesystem device tree, but the hardware address is the right one (4021000), so.... it's that)

now,
SV6256P chip on my board is made by Icomm (aka IcommSemi, aka iComm-semi, aka "Shenzhen iComm Semiconductor Co., Ltd."  , but 
in SDIO_INFO1 we find another company name: South Silicon Valley (SSV); 
SSV produced a chip called SSV6256P, 

moreover my card's SDIO_ID is the same of the old SSV6256P (3030:3030)
and the specs of the two chips seem the same
( Icomm SV6256P in brief : http://www.icomm-semi.com/Product/info/id/53.html#SV6256P

full datasheet is here :
http://www.icomm-semi.com/Uploads/Temp/files/2022-08-19/SV6256P%20Datasheet_V1.0.pdf. I couldn't find a datasheet for SSV6256P but on chinese sites there are lots of resources , look at https://download.csdn.net/download/lihuan680680/20670850, for example)

So, it seems (as reported by others on armbian forums) that SSV and SV are the same wifi chip family.

Now, 
The original SSV6256P has a driver (ssv6x5x) working under armbian (RK3xxx SOC) , but it works only on kernel 4.4.something

from 12656-csc-armbian-for-rk322x-tv-boxes/page/18/ :
"the ssv6x5x is only for ssv6256p chip. People at SSV company are not very well acquainted with names and IDs, in fact they used the very same ID 3030:3030 for both ssv6051 and ssv6256p wifi chips and the driver name is also confusing (looking at ssv6x5x you may think it works for ssv6051 too, but it doesn't  )"

ssv6x5x driver is also been adapted for the "Khadas vim3" board (amlogic A311, and maybe also s905, (linux kernel v?) ) , here 
https://github.com/khadas/android_hardware_wifi_icomm_drivers_ssv6xxx/commit/b8af0da29733b1edd15e91a0bfef3a832927c8d1
if (verify) the driver port for khadas also needs an old kernel....  i'd say not to spend time trying to port the driver to some new kernel.

Thanx for your work.

**Comment by warpme** [comment]
Well,
1. There is no 6.3 code for this chip.
2. support 2 different silicons acting with the same ID is NIGHTMARE

By above I tend to close this ticket with status: closed due no support planned for this hw.
Will it be ok?

**Comment by mercs759** [comment]
as I wrote above "i'd say not to spend time trying to port the driver to some new kernel." ;) 
yep I would close the ticket.

**Comment by warpme** [comment]
closed due no support planned for this hw

**Comment by slckgms** [comment]
For anyone finding this later: the "no 6.x code for this chip" part is out of date. https://github.com/cdhigh/armbian_sv6256p builds on modern kernels, and I have it running as a module on an H616 box against a stock 6.12 Armbian kernel.

Two build gotchas on arm64, both needed: drop `-fpatchable-function-entry=0` from the driver's `config_common.mak` (it overrides the kernel's `=4,2` and the module then won't load), and make sure `CONFIG_DEBUG_INFO_BTF_MODULES` matches between your headers' `.config` and the running kernel, or `struct module` comes out the wrong size.

Not asking to reopen anything, just leaving the pointer: https://github.com/slckgms/h616-sv6256p-wifi-ethernet
