### ISSUE TITLE
FUSE Module Missing? Can't mount NTFS!

### ISSUE THREAD

**Issue by adyatan** [warpme/miniarch#13]
I tried mounting external HDD. First installed ntfs-3g, then used the mount command which gave the following error.
`modprobe: FATAL: Module fuse not found in directory /lib/modules/6.3.1`
`fuse: device not found, try 'modprobe fuse' first`

Doing `modprobe fuse` also gave the same message.
`modprobe: FATAL: Module fuse not found in directory /lib/modules/6.3.1`

**Comment by mercs759** [comment]
if you just have to mount an hard disk, I think doing it as root could help.

**Comment by adyatan** [comment]
Same thing with root.

**Comment by mercs759** [comment]
from arch Linux wiki, May 2023
voice "NTFS"

"Note:
All officially supported kernels with versions 5.15 or newer are built with CONFIG_NTFS3_FS=m and thus support it. Before 5.15, NTFS read and write support is provided by the NTFS-3G FUSE file system. Or you can use backported NTFS3 via ntfs3-dkmsAUR.
Paragon Software, the author of the kernel module, has not yet released userspace utilities for NTFS3. You can use NTFS-3G userspace utilities without NTFS-3G driver via ntfsprogs-ntfs3AUR"

**Comment by adyatan** [comment]
@mercs759 thanks! How couldn't I see that?
Using ntfs3 instead of ntfs-3g successfully mounted the HDD.
