### ISSUE TITLE
about TV box H313-EMCP-V1.0

### ISSUE THREAD

**Issue by jmsvigno** [warpme/miniarch#21]
my tv box uses the same chip,Ik316=h313, but whe I use 
MiniArch-20230212-6.3.5-board-h313.x96_q_lpddr3-SD-Image.img.xz  on boot  says this error: 

U-Boot SPL 2021.04 (May 25 2023 - 13:06:08 +0200)
DRAM:This DRAM setup is currently not supported.

 Attached I send the android original  boot log and the images of my tvbox 

![ik316](https://github.com/warpme/miniarch/assets/143033468/5f02b68d-32a2-4fec-8d66-15a15f55e8eb)
![ik3161](https://github.com/warpme/miniarch/assets/143033468/5797d3bc-f9ed-4810-b952-38107d5bbbe1)
[bootik316.txt](https://github.com/warpme/miniarch/files/12422956/bootik316.txt)

**Comment by warpme** [comment]
Hi,
In boot log i see axp806 pmic....
But can't verify this on picture.
What PMIC your's board uses?
Also - may you get android DT from this box? (instructions howo are in minimyth2 wiki)

**Comment by jmsvigno** [comment]
this chip is axp305 accordingly  this picture  above

I don't know  get Dt android , but I'll try

Also - may you get android DT from this box? (instructions howo are in minimyth2 wiki) ( what is the link for me to try?)

**Comment by warpme** [comment]
Ah this explains a bit issue.
MiniArch-20230212-6.3.5-board-h313.x96_q_lpddr3-SD-Image.img.xz is for lpddr3 and axp1530
Your box has lpddr3 (albeit with different timmings) - but has axp305 pmic
To have running MiniAarch on your box i need:
1. build different bootloader 
2. update lpddr3 dram timings
For p.2 i need access to real hardware (tvbox you are using)
If anybody provide me hardware - i can work on support...

**Comment by jmsvigno** [comment]
> this chip is axp305 accordingly this picture above
> 
> I don't know get Dt android , but I'll try
> 
> Also - may you get android DT from this box? (instructions howo are in minimyth2 wiki) ( what is the link for me to try?)

**Comment by jmsvigno** [comment]
> > this chip is axp305 accordingly this picture above
> > I don't know get Dt android , but I'll try
> > Also - may you get android DT from this box? (instructions howo are in minimyth2 wiki) ( what is the link for me to try?)


I was able to extract the dtb files along with the boot.img and bootloader.img. I can't send you a hardware, but I'm sending the files that I dumped. The link is below because I couldn't attach it here.

[https://we.tl/t-xp8WGoP80f](https://we.tl/t-xp8WGoP80f)

**Comment by jmsvigno** [comment]
I was able to extract the dtb files along with the boot.img and bootloader.img. I can't send you a hardware, but I'm sending the files that I dumped. The link is below because I couldn't attach it here.

https://we.tl/t-xp8WGoP80f

**Comment by warpme** [comment]
Closing due lack of HW to develop support for this variant of h313 tv box

**Comment by jmsvigno** [comment]
@warpme 
I managed to get the TVbox to work, I had to edit the u-boot defconfig with the emcp RAM parameters, but now when using miniarch, it gets stuck according to the error below:

 platform regulatory.0: Falling back to sysfs fallback for: regulatory.db
FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
OK [0m] Mounted /boot [0m.
OK [0m] Started Network Configuration
 OK Reached target  Local File Systems [0m.
         Starting Rebuild Dynamic Linker Cache [0m...
         Starting Create Volatile Files and Directories [0m...
 How can I fix it?
