### ISSUE TITLE
Ethernet interface not available

### ISSUE THREAD

**Issue by PBugalho** [warpme/miniarch#22]
Hi,

I have a X96Q box and I was able to run the "MiniArch-20230212-6.3.5-board-h313.x96_q_lpddr3-SD-Image.img.xz" whitout any initial problem. It boots correctly but when I check the available network interfaces (ifconfig), I only have the loopback  and the wifi interfaces available. The ethernet interface is not available. 

Any ideia why? Am I missing something?
![IMG_20230904_233514](https://github.com/warpme/miniarch/assets/144070560/19b14388-58c5-4285-ab01-bf9857df73fe)

Thank you very much.

**Comment by warpme** [comment]
Hi,
Without output from uart i can't say where issue is.
Is is possible for you to provide uart output from booting process?

**Comment by PBugalho** [comment]
Hi,

Thank you for your help.
Please find attached the android and the miniarch UART boot outputs.

When listing the available interfaces I noticed that the loopback interface is the number one and the wlan0 is the number three. So it should exist a number two in between them that would be the eth0.
[alarm@alarm ~]$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 02:80:e1:0a:96:56 brd ff:ff:ff:ff:ff:ff
[alarm@alarm ~]$

[AndroidBoxBoot.txt](https://github.com/warpme/miniarch/files/12529042/AndroidBoxBoot.txt)
[MiniarchBoot.txt](https://github.com/warpme/miniarch/files/12529043/MiniarchBoot.txt)

Thank you once again.

**Comment by warpme** [comment]
Well - it looks your board (v1.3) has mac phy on different address:
Boot log says:
`Could not get PHY for ethernet@5030000: addr 0`

I just verified all boots ok on my x96-q v1.2 box.

Unfortunately android bootloader also not enables Eth:
`[02.057]No ethernet found.`
so i can't deduce what wiring v1.3 pcb has for Eth phy...

If anybody will provide me HW - i can try to find correct addr....

**Comment by warpme** [comment]
Closing due lack of HW to develop support for this variant of h313 tv box

**Comment by kerta1n** [comment]
Image at the time of writing confirmed working ethernet on boards with the RAM/MMC combo listed (2G-16 instead of HX-JA)
