### ISSUE TITLE
screen stuck at boot

### ISSUE THREAD

**Issue by jmsvigno** [warpme/miniarch#25]
@warpme
 when using miniarch, it gets stuck according to the error below:

platform regulatory.0: Falling back to sysfs fallback for: regulatory.db
FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
OK [0m] Mounted /boot [0m.
OK [0m] Started Network Configuration
OK Reached target Local File Systems [0m.
Starting Rebuild Dynamic Linker Cache [0m...
Starting Create Volatile Files and Directories [0m...
In the serial it gets stuck here as per the text above
On the screen there are only images of the penguin
How can I fix it? i used this image : MiniArch-20230212-6.4.3-board-h616.tanix_tx6s_axp313-SD-Image.img.xz

**Comment by bakuuuuus** [comment]
Are You sure You are trying to install it on right box? I had the same issues while trying to boot image for X96Q on X96mini
