### ISSUE TITLE
Install on TVBox based Vontar H618

### ISSUE THREAD

**Issue by Nguyen-Ngoc-Hung** [warpme/miniarch#28]
I have a TVBox based Vontar H618, I successfully installed it with version **MiniArch-20230718-6.4.4-board-h618.vontar_h618-SD-Image.img**, but with current version (**MiniArch-20231112-6.6.8-board-h618.vontar_h618-SD-Image.img**), the TV box cannot start up.
What are the differences between the two versions?
Where can I download older versions?

**Comment by warpme** [comment]
Hi,
Ah - this is side effect of my u-boot update....
may you pls try newer version (with 6.7 kernel)?

**Comment by Nguyen-Ngoc-Hung** [comment]
Thanks
I will try when the release version is out

**Comment by warpme** [comment]
i uploaded it already ....
