### ISSUE TITLE
Won't boot on my X96Q

### ISSUE THREAD

**Issue by pdouby** [warpme/miniarch#30]
Hello, i have X96Q TV box with H313, 2GB RAM and 16GB ROM. I'am not able to boot any of yours H313/H616 images. Image that should work - MiniArch-20231112-6.6.8-board-h313.x96_q-SD-Image.img.xz - ends with this written to the serial line:

U-Boot SPL 2024.01-rc3 (Dec 14 2023 - 21:40:58 +0100)
DRAM: 64 MiB
Failed to set core voltage!   set CPU 792000000hz frequency

RAM chips seems to be Micron D9PFK:
![IMG_1679](https://github.com/warpme/miniarch/assets/112548244/7f8f13d1-093c-4baa-9356-9c45b701167d)

Seems like there is some issue with my PMIC AXP1530/AXP313... I tried also MiniArch-20231112-6.6.8-board-h616.tanix_tx6s_axp313-SD-Image.img.xz which you edited for that PMIC, but booting stuck on "sun50i-cpufreq-nvmem: will use speed0 CPU OPPs"... So looks like i need combination of both images - H313 CPU and AXP1530/AXP313 PMIC...

Thank you!

Android boot log:

[109]HELLO! BOOT0 is starting!
[112]BOOT0 commit : 3ae35eb
[115]set pll start
[118]periph0 has been enabled
[121]set pll end
[123]unknow PMU
[124]unknow PMU
[126]PMU: AXP1530
[128]dram return write ok
[131]board init ok
[133]DRAM BOOT DRIVE INFO: V0.648
[136]the chip id is 0x5c00
[139]chip id check OK
[144]DRAM_VCC set to 1500 mv
[147]DRAM CLK =600 MHZ
[149]DRAM Type =3 (3:DDR3,4:DDR4,7:LPDDR3,8:LPDDR4)
[157]Actual DRAM SIZE =2048 M
[160]DRAM SIZE =2048 MBytes, para1 = 30fb, para2 = 8000000, dram_tpr13 = 6041
[173]DRAM simple test OK.
[175]rtc standby flag is 0x0, super standby flag is 0x0
[181]dram size =2048
[184]card no is 2
[185]sdcard 2 line count 8
[188][mmc]: mmc driver ver 2021-10-12 13:56
[192][mmc]: b mmc 2 bias 4
[201][mmc]: Wrong media type 0x0, but host sdc2, try mmc first
[207][mmc]: ***Try MMC card 2***
[234][mmc]: RMCA OK!
[287][mmc]: MMC 5.0
[289][mmc]: HSSDR52/SDR25 8 bit
[293][mmc]: 50000000 Hz
[295][mmc]: 15028 MB
[297][mmc]: ***SD/MMC 2 init OK!!!***
[374]Loading boot-pkg Succeed(index=0).
[377][mmc]: b mmc 2 bias 4
[380]Entry_name        = u-boot
[389]Entry_name        = monitor
[393]Entry_name        = dtbo
[396]Entry_name        = dtb
[400]tunning data addr:0x4a0003e8
[403]Jump to second Boot.
NOTICE:  BL3-1: v1.0(debug):05d6c57
NOTICE:  BL3-1: Built : 13:35:35, 2021-10-28
NOTICE:  BL3-1 commit: 8
NOTICE:  cpuidle init version V1.0
ERROR:   Error initializing runtime service tspd_fast
NOTICE:  BL3-1: Preparing for EL3 exit to normal world
NOTICE:  BL3-1: Next image address = 0x4a000000
NOTICE:  BL3-1: Next image spsr = 0x1d3

U-Boot 2018.05 (Jul 22 2023 - 11:53:53 +0800) Allwinner Technology

[00.481]CPU:   Allwinner Family
[00.484]Model: sun50iw9
I2C:   ready
[00.488]DRAM:  2 GiB
[00.491]Relocation Offset is: 75ebf000
[00.534]secure enable bit: 0
[00.536]pmu_axp152_probe pmic_bus_read fail
[00.540]PMU: AXP1530
[00.546]CPU=1008 MHz,PLL6=600 Mhz,AHB=200 Mhz, APB1=100Mhz  MBus=400Mhz
[00.554]drv_disp_init
[00.584]__clk_enable: clk is null.
[00.590]drv_disp_init finish
[00.592]gic: sec monitor mode
[00.622]flash init start
[00.624]workmode = 0,storage type = 2
[00.628]MMC:     2
[00.629][mmc]: mmc driver ver uboot2018:2021-07-19 14:09:00
[00.635][mmc]: get sdc_type fail and use default host:tm4.
[00.647][mmc]: SUNXI SDMMC Controller Version:0x40502
[00.692][mmc]: Best spd md: 4-HS400, freq: 3-100000000, Bus width: 8
[00.698]sunxi flash init ok
[00.702]Loading Environment from SUNXI_FLASH... OK
[00.711]usb burn from boot
delay time 0
weak:otg_phy_config
[00.725]usb prepare ok
[01.528]overtime
[01.532]do_burn_from_boot usb : no usb exist
[01.536]boot_gui_init:start
FAT: Misaligned buffer address (bbe7b598)
32 bytes read in 4 ms (7.8 KiB/s)
tcon_de_attach:de=0,tcon=2[01.669]boot_gui_init:finish
[01.673]bmp_name=bootlogo.bmp
3686456 bytes read in 23 ms (152.9 MiB/s)
[01.712]update dts
** Unrecognized filesystem type **
[01.722]load file(ULI/factory/rootwait init.txt) error.
** Unrecognized filesystem type **
[01.736]load file(ULI/factory/snum.txt) error.
[01.740]name in map mac
** Unrecognized filesystem type **
[01.751]load file(ULI/factory/wifi_mac.txt) error.
** Unrecognized filesystem type **
[01.764]load file(ULI/factory/bt_mac.txt) error.
** Unrecognized filesystem type **
[01.777]load file(ULI/factory/selinux.txt) error.
** Unrecognized filesystem type **
[01.791]load file(ULI/factory/specialstr.txt) error.
[01.802]update part info
[01.833]update bootcmd
[01.835]No ethernet found.
Hit any key to stop autoboot:  0
[02.018]Starting kernel ...

**Comment by pdouby** [comment]
UPDATE:
I managed to boot MiniArch-20231112-6.6.8-board-h616.tanix_tx6s_axp313-SD-Image.img.xz. After few times pluging-unpluging power adapter, it sometimes starts up. It somehow works, but ethernet is very unstable.

**Comment by aldolo69** [comment]
> UPDATE: I managed to boot MiniArch-20231112-6.6.8-board-h616.tanix_tx6s_axp313-SD-Image.img.xz. After few times pluging-unpluging power adapter, it sometimes starts up. It somehow works, but ethernet is very unstable.

hi. did you use the stick-in-avplug to force the boot from sd?

**Comment by pdouby** [comment]
> > UPDATE: I managed to boot MiniArch-20231112-6.6.8-board-h616.tanix_tx6s_axp313-SD-Image.img.xz. After few times pluging-unpluging power adapter, it sometimes starts up. It somehow works, but ethernet is very unstable.
> 
> hi. did you use the stick-in-avplug to force the boot from sd?

Hi, nope. I just plug power adapter in. Sometimes it boots on the first try, sometimes not even on the tenth try. I don't know where is the problem...
But when i finally manage to boot it up, everything (probably except remote control) somehow works. Wi-Fi, HDMI sound works well, ethernet is let's say usable after installing LXQt with NetworkManager (still sometimes dropping packets...). Media playback in web browsers are unusable but Kodi playback works fine in 720p or lower resolution.

**Comment by aldolo69** [comment]
> > > UPDATE: I managed to boot MiniArch-20231112-6.6.8-board-h616.tanix_tx6s_axp313-SD-Image.img.xz. After few times pluging-unpluging power adapter, it sometimes starts up. It somehow works, but ethernet is very unstable.
> > 
> > 
> > hi. did you use the stick-in-avplug to force the boot from sd?
> 
> Hi, nope. I just plug power adapter in. Sometimes it boots on the first try, sometimes not even on the tenth try. I don't know where is the problem... But when i finally manage to boot it up, everything (probably except remote control) somehow works. Wi-Fi, HDMI sound works well, ethernet is let's say usable after installing LXQt with NetworkManager (still sometimes dropping packets...). Media playback in web browser is unusable but Kodi playback works fine in 720p or lower resolution.

at last i managed to boot it. sometime it boot in a few attempts, sometime more. when it boot it boot fast, and the screen show 4 linux mascottes. cheched a couple of sd card. maybe i will find an sd better then other. the noname sd was a nogo, the samsung is the one i'm testing now. i've go another verbatim. who know... anyway for the record: i used rufus to burn the image on a 16gb card. power led does not change to blue. alwasys red. wired lan works if connected on boot, but not always. all in all not a good situation.

**Comment by pdouby** [comment]
Ye, I'am using Samsung EVO 64 GB SDXC and RPi imager for writing the image.  Looks like we facing the same problem with booting. Also power led doesn't change to blue when it finally boots up.

**Comment by aldolo69** [comment]
> Ye, I'am using Samsung EVO 64 GB SDXC and RPi imager for writing the image. Looks like we facing the same problem with booting. Also power led doesn't change to blue when it finally boots up. Good point! Looks like it boots in less attempts when button in AV plug is pressed :D

and what about the desktop install? start-5 script always fails because of network problems. now i'm trying the manual approach with "pacman -S xorg-server" but seems a long journey

**Comment by pdouby** [comment]
> > Ye, I'am using Samsung EVO 64 GB SDXC and RPi imager for writing the image. Looks like we facing the same problem with booting. Also power led doesn't change to blue when it finally boots up. Good point! Looks like it boots in less attempts when button in AV plug is pressed :D
> 
> and what about the desktop install? start-5 script always fails because of network problems. now i'm trying the manual approach with "pacman -S xorg-server" but seems a long journey

Yeah as I wrote before, ethernet is very unstable, sometimes it won't obtain an IP address from network, sometimes it does and connection works fine, sometimes it tends to have huge packet loss... Restarting systemd-networkd service sometimes help... Long journey...
I managed to complete all steps from "Quick start" and then i installed LXQt desktop using this guide:
https://www.debugpoint.com/lxqt-arch-linux-install/

**Comment by aldolo69** [comment]
> > > Ye, I'am using Samsung EVO 64 GB SDXC and RPi imager for writing the image. Looks like we facing the same problem with booting. Also power led doesn't change to blue when it finally boots up. Good point! Looks like it boots in less attempts when button in AV plug is pressed :D
> > 
> > 
> > and what about the desktop install? start-5 script always fails because of network problems. now i'm trying the manual approach with "pacman -S xorg-server" but seems a long journey
> 
> Yeah as I wrote before, ethernet is very unstable, sometimes it won't obtain an IP address from network, sometimes it does and connection works fine, sometimes it tends to have huge packet loss... Restarting systemd-networkd service sometimes help... Long journey... I managed to complete all steps from "Quick start" and then i installed LXQt desktop using part 2 of this guide: https://www.debugpoint.com/lxqt-arch-linux-install/

thankyou for the suggestions. i managed to install the desktop. i miss some icons. from the hardware point of view everything works fine with the exception of the initial boot and the unaccelerated display of course. sure there is a trick to get better result on the initial boot

**Comment by warpme** [comment]
Closed due no hardware to work on.

**Comment by aldolo69** [comment]
> bout the de

in case you are still interested: have found that boot always fails with "sun50i-cpufreq-nvmem: will use speed0 CPU OPPs" in the log. i'm preparing a self-reset with arduino in case of such event, just for fun. i know arduino better then i know linux on arm...
