### ISSUE TITLE
Openvfd on tanix tx6s

### ISSUE THREAD

**Issue by sunilsankar** [warpme/miniarch#39]
Is there a way to enable the led on miniarch. Amazing work btw

**Comment by warpme** [comment]
Well - miniarch uses the same kernel like minimyth2 so openvfd kernel module should work out-of-box...
Do you have in dmesg any openvfd entries?

**Comment by sunilsankar** [comment]
Dont see any module 
```
root@tanix ~]# dmesg |grep -i vfd
[root@tanix ~]#

```

**Comment by warpme** [comment]
Right. If you do `modprobe openvfd` then dmesg should show us kernel talks to 7-seg display hw.
To use 7-seg display you need userspace app https://github.com/arthur-liberman/linux_openvfd It talks to kernel.

**Comment by sunilsankar** [comment]
Thanks now it works 😄.Is it possible to share the miniarch code base I will include the steps and also the service file

**Comment by warpme** [comment]
Well - for miniarch code - i'm already doing this: https://github.com/warpme/minimyth2/tree/master/script/miniarch
User-space of miniarch is in fact ArchLinux ARM - so i think isn't be best when you will start AUR project for user-space OpenVFD?

**Comment by sunilsankar** [comment]
> Well - for miniarch code - i'm already doing this: https://github.com/warpme/minimyth2/tree/master/script/miniarch
> User-space of miniarch is in fact ArchLinux ARM - so i think isn't be best when you will start AUR project for user-space OpenVFD? 

Agreed
