### ISSUE TITLE
x96 mini - compatibility question

### ISSUE THREAD

**Issue by iodn** [warpme/miniarch#40]
Hello,

I recently ordered an x96 mini and it seems to have an Allwinner H313 SoC and a SKhynix
H9TKNNN2G8A ram chips. I was wondering if any of the pre-built versions you made are compatible with it?

Here is a picture of the board just in case:

![IMG_20240613_175452](https://github.com/warpme/miniarch/assets/114117719/1fb49d97-546f-4c10-9322-e6edab1614d8)

![IMG_20240613_182219](https://github.com/warpme/miniarch/assets/114117719/35c4fa7a-d45a-4c92-9884-61805a5a7c97)

**Comment by warpme** [comment]
you may try
but usually getting boot will require to have such hw in my lab.
without access to hw I can't help
sorry
