### ISSUE TITLE
Can't install desktop environment - X96Q

### ISSUE THREAD

**Issue by bladyle** [warpme/miniarch#42]
Hello, 
I'm glad that there is finally support for this TV box and I give it a try. 
I'm installing on SD card and all good until last step - install https://arm.endeavouros.com/ by typing 'start' then (5)
Trying to follow the instruction but it can't finish successful installation: 

Installing EndeavourOS Base Addons...
./endeavour-ARM-install-V2.7.sh: line 111: eos-packagelist: command not found
error: argument '-' specified with empty stdin

Installing EndeavourOS Base Addons   OK

...

Creating ll alias...
Creating ll alias  OK
./endeavour-ARM-install-V2.7.sh: line 909: eos-rankmirrors: command not found
error: could not register 'endeavouros' database (database already registered)

...

nstalling XFCE4 ...
./endeavour-ARM-install-V2.7.sh: line 653: eos-packagelist: command not found
error: argument '-' specified with empty stdin

...

**Comment by kipz** [comment]
@bladyle yeah, I hard that problem too. I was able to install an environment manually using `pacman` directly though.

**Comment by bladyle** [comment]
> @bladyle yeah, I hard that problem too. I was able to install an environment manually using `pacman` directly though.

Can you share some quick instruction? I can't see to load to login screen.

**Comment by kipz** [comment]
> > @bladyle yeah, I hard that problem too. I was able to install an environment manually using `pacman` directly though.
> 
> Can you share some quick instruction? I can't see to load to login screen.

It's all a bit hacky to be honest, but you you need packages that give you xinit/startx and a window manager (e.g. fluxbox).

I don't recall exactly what I did, but hopefully that's enough to get going.

These are my notes:
https://gist.github.com/kipz/93caf0f38944aa726d48135d7261b605

**Comment by warpme** [comment]
As this is not miniarch bug but rather archlinux arm bug - may we close this ticket?

**Comment by bladyle** [comment]
@warpme are you able to do successful step (5) - Installing EndeavourOS on this board ?

**Comment by warpme** [comment]
Please - investigate this issue with EndeavourOS team.
Also I have frequent issues with install of EndeavourOS - mainly due various issues with EndeavourOS install script :-(

**Comment by bladyle** [comment]
Ok, don't worry you can close this issue.
