### ISSUE TITLE
Error copy to emmc 

### ISSUE THREAD

**Issue by letsplaysfax** [warpme/miniarch#43]
Can't determine usage on mmcblk0p
![20240618_001819](https://github.com/warpme/miniarch/assets/161867358/d40ff357-19fa-42da-926b-cb701a3c4543)

**Comment by warpme** [comment]
Hi,
Is this from latest ver?
If so - pls provide me /var/log/install-on-emmc.log

**Comment by letsplaysfax** [comment]
> Hi, Is this from latest ver? If so - pls provide me /var/log/install-on-emmc.log

done after change another micro sd
