### ISSUE TITLE
X96Q - won't boot

### ISSUE THREAD

**Issue by mi6e4ka** [warpme/miniarch#47]
Hello! I try to install MiniArch-20240715-6.10.0-board-h313.x96_q-SD-Image.img on my x96q tv box, with label "BA301_141 V4.0" on board. Here uart logs:
```
U-Boot SPL 2024.04 (Jul 15 2024 - 09:49:43 +0200)
DRAM: 2048 MiB
spl: mmc init failed with error: -1
SPL: failed to boot from all boot devices
### ERROR ### Please RESET the board ###
```
I try with two different sd card (16gb and 32gb, sdhc, class 4 and 10), but result is the same.

Upd:
![PXL_20240720_005412152](https://github.com/user-attachments/assets/c75154a7-cf5f-465f-bee9-f964559c659f)
(Under radiator "h313")
![PXL_20240720_005505285 MV](https://github.com/user-attachments/assets/d04e2e14-d1b6-4ab0-8966-ffcd05ab7671)
p.s. sorry for bad photos quality, haha

**Comment by warpme** [comment]
well - without having this hw in my lab I can help...
sorry

**Comment by mi6e4ka** [comment]
@warpme What could be the problem? I can provide all the necessary information

**Comment by warpme** [comment]
...without having this hw in my lab....
