### ISSUE TITLE
Support wireless for tanix tx68 

### ISSUE THREAD

**Issue by phubh** [warpme/miniarch#49]
This device uses CPU Allwiner H618 Ram 2/4 DDR3. I installed miniarch on this devices but wireless features look like not work 
![photo_2024-07-24_11-36-26](https://github.com/user-attachments/assets/33e7c927-7463-4443-8a12-57ccaf3bc171)

**Comment by warpme** [comment]
Well - without having this HW in my lab I can't help.
Sorry....
