### ISSUE TITLE
Support for H96 MAX Allwinner H616 Ethernet

### ISSUE THREAD

**Issue by 1gordingoxtozo** [warpme/miniarch#7]
Hello,

I have a H96 MAX TV Box with Allwinner H616 SoC, i could boot using the OrangePi Zero 2 image but i have the problem like all others OS's that i tried (Armbian, OrangePi Zero 2) the ethernet is not recognized. I have been searching for help in many forums but couldn't find nothing that could help.

This is the photos that i took from the TV Box PCB with all chips, if you please could add drivers for this ethernet chip or tell me how to do that, i would really appreciate that. HCY6334 is the module with the metal protection
![photo_2023-02-22_16-26-20 (2)](https://user-images.githubusercontent.com/126110290/220737926-9b98713b-4571-441c-b2d4-2af395a7108b.jpg)
![photo_2023-02-22_16-26-20](https://user-images.githubusercontent.com/126110290/220737931-a43e5298-e02b-44b0-a0b7-d01a7f3c999a.jpg)

**Comment by warpme** [comment]
May you pls try with sun50i-h616-t95.dtb ?

Procedure: pls look https://github.com/warpme/minimyth2/wiki/Running-on-ARM-boards-or-TVboxes#quick-start-guide

it will be useful to have dmesg output from each try…

**Comment by warpme** [comment]
Closed due no replay from issue reporter.
