### ISSUE TITLE
miniarch 20230212 h313.x96_q-SD on Andowl Q96x (H313, 2GB/16GB)

### ISSUE THREAD

**Issue by mercs759** [warpme/miniarch#9]
Hello, 
Presenting my system and my first Miniarch install:

System :
cardboard packaging says "Andowl box Q96X" ,"4Gb RAM, 64Gb Rom, Android 12", but 
- RAM is only 2GBytes
- rom is only 16Gb (see after) 
- HWinfo says "Android 12" it's a fake android 10.

Ports (left to right) : 12volt in, optical spdif, hdmi, ethernet, AV minijack(with button inside) / 2xUSB,  ; microsd,
Blue, Square PCB
PCB side A: 
- pcb marked X88PROA-H313-D4-V1.0	2020-11-20
- cpu : h313(?, not verified) covered by a small heatsink
- eMMc 5.0 16gb samsung  klmag2gend-b031
- 4 samsung modules SEC XXX hyh9 k4b2g0446c DDR3-1333(667mhz) SDRAM sodimm (1GByte)
- AXP305 chip : Power Management IC (PMIC)
- TF1102 . 2237T chip (brand : ?TC)
- Wifi chip on SDIO bus: SV6256P (aka South Silicon Valley's SSV6256P),  150 mbps max a/b/g/n, 
- Vacuum Fluorescent Display (VFD) info panel : 4 characters (88:88) 7segments each. Shows "LoAd" while android10 Is loading, then time + On/off + "WIFI" + "LAN"

PCB side B :
- 4 samsung modules (another 1GB, total 2GB) 
- AIP1628 (driver chip for led panel on sideA, ) 
- GND RX TX pinholes 
- CP-FB GP-FB (related to PMIC on side A)

Before installing miniarch I did some HW tests wirh the stock Android 10, using CPUZ and other softwares : 
in android, doing very little, cpu temp is quite high (60°C), box seems warm. CPU frequency seems to be always about 1280mhz, RAM & eMMC reported sizes are wrong.

MINIARCH INSTALL   :
Downloaded MiniArch-20230212-6.2.11-board-h313.x96_q-SD-Image.img
On Win10pro-64 I used Usbimager 1.0.9 to write .xz image on a old 2GB microsd 

Q96X box is off,  hdmi cable is attached, nothing else is connected

Put the micro SD in 

- 1st try :
I kept hidden AV button pressed with toothpick and plug AC adapter while pressing, waited 6 seconds, released toothpick, waited for 30 minutes
Nothing seems to happen: 
So I disconnected the AC adapter. 
(I don't know if this did something to the bootloader or if it was a required step, but I did it XD)

- 2nd try
just plug only AC adapter in
result : 
Arch Linux 6.2.11 (tty)
alarm login :

plugged in an HP usb italian keyboard, 
login root, password root, start , option 2 (and [enter], or u will wait forever ;DD )

"start", option 1 : lots of errors (i didn't know I needed an internet connection ;D) 
plug an ethernet cable in, box obtains everything from my DHCP server
again "start", option 1 : some warnings about versions 

" Packages (106) , tot Download size : 71.86Mib , Tot installed size 327,00 Mib, Net upgrade size : 25,27 Mib
Proceed with instal? Y"

installing , (box is almost cold, everything seems going ok.)
some warnings ( server 'gpg agent' is older than us (2.2.36 < 2.2.41)

System asked to reboot : Y
screen went blank and so remained : box was almost cold, I waited 3 hours for an auto-reboot, but nothing. At last I surrendered, and plugged off the AC adapter's plug.

re-plug ACadapter in, miniarch started
did repartitioning (option 3) and updated Miniarch Artefacts

reboot. This time reboot went ok :-))

System seems stable. 
CPU performance is similar or better than that under stock android10 ROM.
Heat management is ok.

MAJOR PROBLEMS (Update, most of those have been fixed as of latest update (6.3) ): 

- CPU scaling/governor seems broken (moved to issue #11 ) (fixed with updates.)
- thermal sensors need calibration : 
CPU's heatsink is almost cold, but system reports 84° (also moved to issue #11 ) (fixed)

- WIFI chip (sv6256P) is detected on the SDIO bus, and a node is created in the filesystem under "mmc3", but no working driver exists for sv6256P chip under linux kernels >4.4.x (Will not be fixed, too much work)
more about this wifi chip is in issue #10 .

Minor troubles :
- sometimes plugging AC adapter doesn't make system start. You need to plug out and in again.
- no cursor in local access. (but it's ok in ssh) (fixed)
- no sign of life coming from my box when system is ON : VFD is off (fixed, just find right settings for openVFD)

Still to be tested
- Audio (analog and Optical SPdif) (for SPDIF android10 uses sunxi-spdif, sndspdif and spdif-utils). But Alwinner's SPdif seems to be very little documented.
- IR remote
- GPU/video acceleration
- EndeavourOS Desktop

Requests (please) :
- reduce SDcard writings at minimum: logs writing etc...
- include some testing/hwinfo CLI software by default (lshw, p7zip, s-tui...)
- please add in instructions : 
  "minimum SD card size : Miniarch 202302 only, 2GB ; Miniarch + Endeavour OS,  4GB (headless) or xxGB (desktop)"

**Comment by warpme** [comment]
closed due inactivity...
